openapi: 3.0.0
info:
  title: Order Service API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /orders:
    $ref: "./paths/orders.yaml"
  /orders/{order_uuid}:
    get:
      $ref: "./paths/order_by_uuid.yaml"
  /orders/{order_uuid}/pay:
    post:
      $ref: "./paths/order_pay.yaml"
  /orders/{order_uuid}/cancel:
    post:
      $ref: "./paths/order_cancel.yaml"
components:
  schemas:
    CreateOrderRequest:
      $ref: "./components/create_order_request.yaml"
    CreateOrderResponse:
      $ref: "./components/create_order_response.yaml"
    OrderDto:
      $ref: "./components/order_dto.yaml"
    GetOrderResponse:
      $ref: "./components/get_order_response.yaml"
    PayOrderRequest:
      $ref: "./components/pay_order_request.yaml"
    PayOrderResponse:
      $ref: "./components/pay_order_response.yaml"
    OrderStatus:
      $ref: "./components/enums/order_status.yaml"
    PaymentMethod:
      $ref: "./components/enums/payment_method.yaml"
    BadRequestError:
      $ref: "./components/errors/bad_request_error.yaml"
    NotFoundError:
      $ref: "./components/errors/not_found_error.yaml"
    ConflictError:
      $ref: "./components/errors/conflict_error.yaml"
    InternalServerError:
      $ref: "./components/errors/internal_server_error.yaml"
  parameters:
    OrderUuid:
      $ref: "./params/order_uuid.yaml"