name: CI

on:
  push:
    branches: [main, hw_3]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint-reusable.yml

  test:
    uses: ./.github/workflows/test-reusable.yml

  coverage:
    uses: ./.github/workflows/test-coverage-reusable.yml
    secrets:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
