name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.5

      - name: Run linter for inventory
        run: |
          cd inventory
          golangci-lint run ./...
        continue-on-error: true

      - name: Run linter for order
        run: |
          cd order
          golangci-lint run ./...
        continue-on-error: true

      - name: Run linter for payment
        run: |
          cd payment
          golangci-lint run ./...
        continue-on-error: true
